services:
  - type: web
    name: recovery-app
    runtime: python
    buildCommand: pip install -r requirements.txt && chmod +x start.sh
    startCommand: ./start.sh
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: TELEGRAM_TOKEN
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: RENDER_URL
        sync: false
